Repository BC-MAY-21-ROR/kata-06-reloj-checador-k06-t01, pull requests merged in 2021-07, with the labels that each got.

#13 Enhancement#12/test environment
  reloj-checador/.rspec
  reloj-checador/Gemfile
  reloj-checador/Gemfile.lock
  reloj-checador/spec/rails_helper.rb
  reloj-checador/spec/spec_helper.rb
  reloj-checador/spec/support/factory_bot.rb
Labels: mentor review required, ready for review

#22 Migration#18/creation of models
  reloj-checador/app/models/attendance.rb
  reloj-checador/app/models/company.rb
  reloj-checador/app/models/employee_attendance.rb
  reloj-checador/config/initializers/inflections.rb
  reloj-checador/db/migrate/20210702204510_create_companies.rb
  reloj-checador/db/migrate/20210702204518_create_attendances.rb
  reloj-checador/db/migrate/20210702204526_create_employee_attendance.rb
  reloj-checador/test/application_system_test_case.rb
  reloj-checador/test/channels/application_cable/connection_test.rb
  reloj-checador/test/controllers/.keep
  reloj-checador/test/fixtures/files/.keep
  reloj-checador/test/helpers/.keep
  reloj-checador/test/integration/.keep
  reloj-checador/test/mailers/.keep
  reloj-checador/test/models/.keep
  reloj-checador/test/system/.keep
  reloj-checador/test/test_helper.rb
Labels: ready for review

#23 Feature#4/authentication
  reloj-checador/Gemfile
  reloj-checador/Gemfile.lock
  reloj-checador/app/controllers/admin_controller.rb
  reloj-checador/app/controllers/application_controller.rb
  reloj-checador/app/controllers/attendance_controller.rb
  reloj-checador/app/models/user.rb
  reloj-checador/app/views/admin/dashboard.html.erb
  reloj-checador/app/views/attendance/check.html.erb
  reloj-checador/app/views/devise/sessions/new.html.erb
  reloj-checador/app/views/devise/shared/_error_messages.html.erb
  reloj-checador/app/views/devise/shared/_links.html.erb
  reloj-checador/app/views/devise/unlocks/new.html.erb
  reloj-checador/app/views/layouts/application.html.erb
  reloj-checador/config/environments/development.rb
  reloj-checador/config/initializers/devise.rb
  reloj-checador/config/locales/devise.en.yml
  reloj-checador/config/routes.rb
  reloj-checador/db/migrate/20210703185032_devise_create_users.rb
  reloj-checador/db/migrate/20210703191219_add_name_to_users.rb
  reloj-checador/db/migrate/20210703191251_add_position_to_users.rb
  reloj-checador/db/migrate/20210703191311_add_employee_number_to_users.rb
  reloj-checador/db/migrate/20210703191325_add_private_number_to_users.rb
  reloj-checador/db/migrate/20210703191331_add_status_to_users.rb
  reloj-checador/db/migrate/20210703191337_add_role_to_users.rb
  reloj-checador/db/schema.rb
  reloj-checador/db/seeds.rb
  reloj-checador/db/seeds/development.rb
Labels: ready for review

#25 Feature#19/references
  reloj-checador/Gemfile.lock
  reloj-checador/app/models/attendance.rb
  reloj-checador/app/models/company.rb
  reloj-checador/app/models/employee_attendance.rb
  reloj-checador/db/migrate/20210704035504_add_attendance_ref_to_employee_attendance.rb
  reloj-checador/db/schema.rb
Labels: ready for review

#28 add bootstrap and font awesome icons
  reloj-checador/Gemfile
  reloj-checador/Gemfile.lock
  reloj-checador/app/assets/stylesheets/application.scss
  reloj-checador/app/javascript/packs/application.js
  reloj-checador/app/views/attendance/check.html.erb
  reloj-checador/db/schema.rb
Labels: ready for review

#35 Feature#34/update bootstrap version
  reloj-checador/Gemfile
  reloj-checador/Gemfile.lock
  reloj-checador/app/assets/config/manifest.js
  reloj-checador/app/assets/stylesheets/application.css
  reloj-checador/app/javascript/packs/application.js
  reloj-checador/app/javascript/stylesheets/application.scss
  reloj-checador/app/views/attendance/check.html.erb
  reloj-checador/app/views/layouts/application.html.erb
  reloj-checador/package.json
  reloj-checador/yarn.lock
Labels: mentor review required, ready for review

#42 Feature#39/login view
  reloj-checador/app/assets/images/check-login.jpg
  reloj-checador/app/javascript/stylesheets/application.scss
  reloj-checador/app/javascript/stylesheets/devise.scss
  reloj-checador/app/views/devise/sessions/new.html.erb
  reloj-checador/db/seeds/development.rb
Labels: ready for review

#41 Feature#40/dashboard view and responsive admin layout
  reloj-checador/app/assets/stylesheets/application.css
  reloj-checador/app/assets/stylesheets/companies.scss
  reloj-checador/app/controllers/admin_controller.rb
  reloj-checador/app/controllers/companies_controller.rb
  reloj-checador/app/helpers/companies_helper.rb
  reloj-checador/app/javascript/stylesheets/application.scss
  reloj-checador/app/javascript/stylesheets/dashboard.scss
  reloj-checador/app/javascript/stylesheets/menu_admin.scss
  reloj-checador/app/javascript/stylesheets/modal-side.scss
  reloj-checador/app/views/admin/dashboard.html.erb
  reloj-checador/app/views/attendance/check.html.erb
  reloj-checador/app/views/companies/_modal_a_e.erb
  reloj-checador/app/views/companies/index.html.erb
  reloj-checador/app/views/layouts/application.html.erb
  reloj-checador/config/routes.rb
  reloj-checador/db/seeds.rb
  reloj-checador/db/seeds/development.rb
Labels: ready for review

#44 Feature#10/employees crud
  reloj-checador/Gemfile
  reloj-checador/Gemfile.lock
  reloj-checador/app/controllers/application_controller.rb
  reloj-checador/app/controllers/employees_controller.rb
  reloj-checador/app/helpers/application_helper.rb
  reloj-checador/app/helpers/company_helper.rb
  reloj-checador/app/models/user.rb
  reloj-checador/app/presenters/employee_presenter.rb
  reloj-checador/app/queries/users_query.rb
  reloj-checador/app/views/employees/_form_fields.html.erb
  reloj-checador/app/views/employees/edit.html.erb
  reloj-checador/app/views/employees/index.html.erb
  reloj-checador/app/views/employees/new.html.erb
  reloj-checador/app/views/employees/show.html.erb
  reloj-checador/app/views/layouts/application.html.erb
  reloj-checador/config/application.rb
  reloj-checador/config/initializers/pagy.rb
  reloj-checador/config/routes.rb
  reloj-checador/db/seeds/development.rb
Labels: mentor review required, ready for review

#58 Feature#54/layout
  reloj-checador/app/helpers/application_helper.rb
  reloj-checador/app/views/admin/dashboard.html.erb
  reloj-checador/app/views/layouts/_sidebar.html.erb
  reloj-checador/app/views/layouts/application.html.erb
Labels: mentor review required, ready for review

#62 Feature#60/modify db
  reloj-checador/app/controllers/attendances_controller.rb
  reloj-checador/app/models/absence.rb
  reloj-checador/app/models/attendance.rb
  reloj-checador/app/models/employee_attendance.rb
  reloj-checador/app/models/user.rb
  reloj-checador/app/views/attendance/check.html.erb
  reloj-checador/config/initializers/inflections.rb
  reloj-checador/db/migrate/20210702204526_create_employee_attendance.rb
  reloj-checador/db/migrate/20210704035504_add_attendance_ref_to_employee_attendance.rb
  reloj-checador/db/migrate/20210706155956_add_user_ref_to_employee_attendance.rb
  reloj-checador/db/migrate/20210722035910_create_absences.rb
  reloj-checador/db/migrate/20210722035958_add_user_ref_to_absences.rb
  reloj-checador/db/migrate/20210722040013_add_user_ref_to_attendances.rb
  reloj-checador/db/migrate/20210722041809_add_type_to_attendances.rb
  reloj-checador/db/schema.rb
  reloj-checador/db/seeds/development.rb
  reloj-checador/spec/factories/companies.rb
  reloj-checador/spec/factories/users.rb
  reloj-checador/spec/models/absence_spec.rb
  reloj-checador/spec/models/attendance_spec.rb
  reloj-checador/spec/models/company_spec.rb
  reloj-checador/spec/models/user_spec.rb
Labels: ready for review

#61 complete update and show for companies
  reloj-checador/app/views/companies/_modal_a_e.erb
  reloj-checador/app/views/companies/index.html.erb
Labels: mentor review required, ready for review

#63 Feature#48/dashboard information
  reloj-checador/app/controllers/admin_controller.rb
  reloj-checador/app/controllers/companies_controller.rb
  reloj-checador/app/controllers/employees_controller.rb
  reloj-checador/app/helpers/application_helper.rb
  reloj-checador/app/helpers/attendance_helper.rb
  reloj-checador/app/helpers/companies_helper.rb
  reloj-checador/app/javascript/packs/company.js
  reloj-checador/app/models/attendance.rb
  reloj-checador/app/queries/absences_query.rb
  reloj-checador/app/queries/attendances_query.rb
  reloj-checador/app/views/admin/dashboard.html.erb
  reloj-checador/app/views/companies/_modal_a_e.erb
  reloj-checador/app/views/companies/index.html.erb
  reloj-checador/app/views/employees/_form_fields.html.erb
  reloj-checador/app/views/employees/index.html.erb
  reloj-checador/app/views/layouts/_sidebar.html.erb
  reloj-checador/config/application.rb
Labels: mentor review required, ready for review

#64 Feature#39/employee check
  reloj-checador/app/controllers/attendances_controller.rb
  reloj-checador/app/views/attendances/check.html.erb
  reloj-checador/config/routes.rb
Labels: mentor review required

#67 Enhancement#65/form validations
  reloj-checador/app/controllers/companies_controller.rb
  reloj-checador/app/controllers/employees_controller.rb
  reloj-checador/app/helpers/application_helper.rb
  reloj-checador/app/models/attendance.rb
  reloj-checador/app/models/user.rb
  reloj-checador/app/views/employees/_form_fields.html.erb
  reloj-checador/spec/factories/users.rb
  reloj-checador/spec/models/attendance_spec.rb
  reloj-checador/spec/models/user_spec.rb
Labels: mentor review required, ready for review

#66 Feature#55/report views
  reloj-checador/app/controllers/reports_controller.rb
  reloj-checador/app/javascript/stylesheets/application.scss
  reloj-checador/app/javascript/stylesheets/attendance.scss
  reloj-checador/app/javascript/stylesheets/average.scss
  reloj-checador/app/javascript/stylesheets/reports.scss
  reloj-checador/app/views/reports/average_time.html.erb
  reloj-checador/app/views/reports/daily_attendance.html.erb
  reloj-checador/app/views/reports/index.html.erb
  reloj-checador/app/views/reports/monthly_absence.html.erb
  reloj-checador/app/views/reports/monthly_attendance.html.erb
  reloj-checador/config/routes.rb
Labels: mentor review required, ready for review

#73 Feaute#70/style check view
  reloj-checador/app/javascript/packs/check.js
  reloj-checador/app/javascript/stylesheets/application.scss
  reloj-checador/app/javascript/stylesheets/check.scss
  reloj-checador/app/views/attendances/check.html.erb
  reloj-checador/config/routes.rb
Labels: mentor review required, ready for review

#75 Feature#48/change employee status
  reloj-checador/app/controllers/employees_controller.rb
  reloj-checador/app/helpers/application_helper.rb
  reloj-checador/app/queries/users_query.rb
  reloj-checador/app/views/employees/index.html.erb
  reloj-checador/config/routes.rb
Labels: mentor review required, ready for review

#76 Feature#72/style employees
  reloj-checador/app/javascript/stylesheets/application.scss
  reloj-checador/app/javascript/stylesheets/employees.scss
  reloj-checador/app/javascript/stylesheets/reports.scss
  reloj-checador/app/views/employees/_form_fields.html.erb
  reloj-checador/app/views/employees/edit.html.erb
  reloj-checador/app/views/employees/index.html.erb
  reloj-checador/app/views/employees/new.html.erb
  reloj-checador/app/views/employees/show.html.erb
  reloj-checador/app/views/reports/index.html.erb
Labels: mentor review required, ready for review

#81 Fix#80/employee check
  reloj-checador/app/controllers/attendances_controller.rb
  reloj-checador/app/helpers/attendance_helper.rb
  reloj-checador/app/javascript/stylesheets/attendance.scss
  reloj-checador/app/javascript/stylesheets/average.scss
  reloj-checador/app/javascript/stylesheets/check.scss
  reloj-checador/app/javascript/stylesheets/companies.scss
  reloj-checador/app/javascript/stylesheets/dashboard.scss
  reloj-checador/app/javascript/stylesheets/devise.scss
  reloj-checador/app/javascript/stylesheets/employees.scss
  reloj-checador/app/javascript/stylesheets/menu_admin.scss
  reloj-checador/app/javascript/stylesheets/modal-side.scss
  reloj-checador/app/javascript/stylesheets/reports.scss
  reloj-checador/app/queries/users_query.rb
  reloj-checador/app/views/attendances/check.html.erb
Labels: mentor review required, ready for review
